name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.target }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.94"
          targets: ${{ matrix.target }}

      - name: Cache cargo registry and build
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Rename binary
        run: cp target/${{ matrix.target }}/release/miden-verify miden-verify-${{ matrix.target }}

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: miden-verify-${{ matrix.target }}

      - name: Upload
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          gh release upload ${RELEASE_TAG} miden-verify-${{ matrix.target }}
